### ISSUE TITLE
what Raspberry Pi OS/image did you use?

### ISSUE THREAD

**Issue by tonzyl** [wimvanderbauwhede/limited-systems#1]
Hi Wim,
Quick question. With which RaspberryPi OS did you do this? I don't think you mention it in your guide. Thanks for writing up the guide. Will try to follow it (although the link to the Jean Brito guide is dead at the mo, will use a cached version if I can find it.)

**Comment by wimvanderbauwhede** [comment]
Sorry for the late reply. My Raspberry Pi is running Raspbian Stretch,  Linux raspberrypi 4.14.34-v7+
Thanks for alerting me that that link is broken. I hope that's not a major hurdle. 
The commands should be like this I think:
## Update the package database
    $ sudo apt-get upgrade

## Install Node
    $ sudo apt-get install nodejs

## Instal rbenv and Ruby 2.4
    $ sudo apt-get install rbenv ruby-build 
    $ echo 'eval "$(rbenv init -)"' >> ~/.bashrc

## Build ruby
    $ rbenv install --list                            
    $ MAKE_OPTS="-j 4" rbenv install 2.4.0           
    $ rbenv global 2.4.0                            

## Check
    $ ruby --version
    => ruby 2.4.0p0 (2016-12-24 revision57164) [armv7l-linux-eabihf]
    $ which ruby
    => /home/pi/.rbenv/shims/ruby

## Install Rails
    $ gem install bundler
    $ gem install rails

## Install Postgresql
    $ sudo apt install postgresql libpq-dev postgresql-client postgresql-client-common -y
