### ISSUE TITLE
make: *** No rule to make target 'uImage'.

### ISSUE THREAD

**Issue by CaptainJL** [wimvanderbauwhede/limited-systems#2]
Hey all,
I have been following every step on Ubuntu, however everytime (tried this multiple times) i get to compiling the uImage, i always get this:

```
 ((xilinx-v2016.4)) ~/PYNQ-Z1/u-boot-xlnx $ make -j8 UIMAGE_LOADADDR=0x8000 uImage
make: *** No rule to make target 'uImage'.  Stop.
```

Any fixes for this?

Thanks,

**Comment by CaptainJL** [comment]
It turns out that you have to go back to the linux-xlnx folder before doing this, which was not stated.

**Comment by wimvanderbauwhede** [comment]
Thanks, I've updated that!
