### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by adamagniv** [wimvanderbauwhede/limited-systems#3]
Hi,
I've read your "Raspbian "stretch" for Raspberry Pi 3 on QEMU" post and I have a problem.
Every time I run the qemu I get this error : Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004. I don't understand why, because I've followed your instructions step by step. If you could help me it'll be great!
Also the latest image is from the 2018-11-13 and the PARTUUID had changed to 7ee80803-02. (I've tried the one from October also and it gave me the same problems...)

**Comment by wimvanderbauwhede** [comment]
The most likely reason for this error is that your image was corrupted, either during download or during unzipping. 
To check if the downloaded zip was correct, you can download the sha1 or sha256 checksum and run the command 

      $ wget https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-10-11/2018-10-09-raspbian-stretch-lite.zip.sha1
      $ shasum 2018-10-09-raspbian-stretch-lite.zip

The checksums should be the same.

To test if the unzipped image is fine, calculate the checksum for the image 

      $ shasum 2018-10-09-raspbian-stretch-lite.img

It should be identical to this:

      c3617147dcd8e02c116141d0d3a64a38d42b720b  2018-10-09-raspbian-stretch-lite.img

**Comment by mannutech** [comment]
Is it working now for the issue creator.
I am facing the same problem on my Ubuntu 16.04

**Comment by wimvanderbauwhede** [comment]
I don't know, he did not reply and I can't reproduce the error. I have not run Ubuntu on Qemu so I can't really help you there.
