### ISSUE TITLE
root partition does not work.

### ISSUE THREAD

**Issue by leoniloris** [wimvanderbauwhede/limited-systems#4]
For me, `root=PARTUUID=ee25660b-02` did not work, but instead: `root=/dev/sda2` did the trick.

**Comment by wimvanderbauwhede** [comment]
They should be equivalent, but maybe you got a more recent image with a different  PARTUUID?

**Comment by leoniloris** [comment]
Either way, if  both are supposed to work, the former is more intuitive.

**Comment by wimvanderbauwhede** [comment]
I agree. The PARTUUID syntax has the advantage of not relying on the name given to the partition, but it is less clear.
