### ISSUE TITLE
qemu versioning and STABLE distro releases

### ISSUE THREAD

**Issue by tempest766** [wimvanderbauwhede/limited-systems#5]
What is the specific requirement for qemu 2.12 and greater?  distro STABLE releases are mostly still at 2.11 and needlessly upgrading individual packages outside of the distro has a habit of causing unintended consqeuences.

**Comment by tempest766** [comment]
At least in 2.11 the -append option will only accept a single parameter following it, regardless of additional quotation such  as -append \\"opt1 opt2 opt3\\".

Also -redir has been depricated before 2.11 so you have to see that warning in 2.12 and later, right?

Only other comment is that the stub board is single core.  Considering that the thing is emulated to begin with, it is unbearably slow.

**Comment by wimvanderbauwhede** [comment]
The raspi3 model was only added in qemu 2.12. I can't tell from your comment which model you used, was it virt or versatilepb (or maybe both)?  If you can clarify this then I will change it to say that 2.11 also works. 

The speed depends a lot on your host system I think, I found it quite bearable.

**Comment by tempest766** [comment]
versatilepb was the machine model I tried.  in qemu 2.11

**Comment by wimvanderbauwhede** [comment]
OK, I've changed the version requirement to 2.11 in the Ubuntu tutorial. Thanks!
