### ISSUE TITLE
rasberi stuck at random:crng init done 

### ISSUE THREAD

**Issue by vivrt** [wimvanderbauwhede/limited-systems#7]
Hello, 

tried run rasberi pi from your instruction on linux and on windows with qemu and loading on both stucking on random: crng init done

> nf_conntrack version 0.5.0 (4096 buckets, 16384 max)
> ip_tables: (C) 2000-2006 Netfilter Core Team
> NET: Registered protocol family 17
> Bridge firewalling registered
> 9pnet: Installing 9P2000 support
> rtc-ds1307 0-0068: setting system clock to 2019-02-09 10:47:51 UTC (1549709271)
> uart-pl011 101f1000.uart: no DMA platform data
> input: ImExPS/2 Generic Explorer Mouse as /devices/platform/amba/amba:fpga/10007000.kmi/serio1/input/input2
> Waiting for root device PARTUUID=ee25660b-02...
> random: crng init done

run command

> qemu-system-arm -kernel raspbian_bootpart/kernel-qemu-4.14.79-stretch    -dtb raspbian_bootpart/versatile-pb.dtb    -m 256 -M versatilepb -cpu arm1176    -serial stdio    -append "rw console=ttyAMA0 root=PARTUUID=ee25660b-02 rootfstype=ext4  loglevel=8 rootwait fsck.repair=yes memtest=1"   -net nic -net user,hostfwd=tcp::5022-:22 -hda 2018-11-13-raspbian-stretch-lite.img  -no-reboot

**Comment by wimvanderbauwhede** [comment]
It is probably because your image is 2018-11-13, so the PARTUUID will be different. Try instead to use 

    root=/dev/sda2

**Comment by vivrt** [comment]
aws ec2 not support qemu or any other virtualization

**Comment by wimvanderbauwhede** [comment]
Ah, so it has nothing to do with the tutorial. Thanks for the update!
