### ISSUE TITLE
feature request: networking

### ISSUE THREAD

**Issue by ghost** [wimvanderbauwhede/limited-systems#8]
Hi,

Succesfully created a qemu-rpi-system! Works like a charm. Only: is it possible to do networking in it somehow?

**Comment by wimvanderbauwhede** [comment]
Hi, both my tutorials (Debian and Raspbian) explain how to do networking. Networking is not supported on the raspi3 board model in Qemu, so I used different board models (virt resp. versatilepb) that have networking support.
